# Form implementation generated from reading ui file 'Convertor.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 390)
        MainWindow.setStyleSheet("background-color: (9, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.valute1 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.valute1.setObjectName("valute1")
        self.valute1.addItem("")
        self.valute1.addItem("")
        self.valute1.addItem("")
        self.valute1.addItem("")
        self.valute1.addItem("")
        self.valute1.addItem("")
        self.verticalLayout.addWidget(self.valute1)
        self.start = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.Convert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Convert.setObjectName("Convert")
        self.verticalLayout.addWidget(self.Convert)
        self.valute2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.valute2.setObjectName("valute2")
        self.valute2.addItem("")
        self.valute2.addItem("")
        self.valute2.addItem("")
        self.valute2.addItem("")
        self.valute2.addItem("")
        self.valute2.addItem("")
        self.verticalLayout.addWidget(self.valute2)
        self.End = QtWidgets.QLabel(parent=self.centralwidget)
        self.End.setMaximumSize(QtCore.QSize(1600, 30))
        self.End.setObjectName("End")
        self.verticalLayout.addWidget(self.End)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТОР ВАЛЮТ"))
        self.valute1.setItemText(0, _translate("MainWindow", "Гривні"))
        self.valute1.setItemText(1, _translate("MainWindow", "Долари"))
        self.valute1.setItemText(2, _translate("MainWindow", "Юані"))
        self.valute1.setItemText(3, _translate("MainWindow", "Злотий"))
        self.valute1.setItemText(4, _translate("MainWindow", "Євро"))
        self.valute1.setItemText(5, _translate("MainWindow", "Фунт"))
        self.start.setText(_translate("MainWindow", "0"))
        self.Convert.setText(_translate("MainWindow", "КОНВЕРТУВАТИ"))
        self.valute2.setItemText(0, _translate("MainWindow", "Гривні"))
        self.valute2.setItemText(1, _translate("MainWindow", "Долари"))
        self.valute2.setItemText(2, _translate("MainWindow", "Юані"))
        self.valute2.setItemText(3, _translate("MainWindow", "Злотий"))
        self.valute2.setItemText(4, _translate("MainWindow", "Євро"))
        self.valute2.setItemText(5, _translate("MainWindow", "Фунт"))
        self.End.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
